DEFAULT_AREA = 350
DEFAULT_AREA_FD = 350
DEFAULT_AREA_BS = 350

DEFAULT_THRESHOLD = 50
DEFAULT_THRESHOLD_BS = 50

DEFAULT_BLUR = 11
DEFAULT_DILT = 15
DEFAULT_LEARNING_RATE = 0.9

AVAILABLE_MODELS = ["Frame Difference", "Background Substraction", "Default"]


DEFAULT_MODEL = "Background Substraction"
